CREATE TABLE `contact_table` (
  `contact_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `number` bigint unsigned DEFAULT NULL,
  `identifier` varchar(255) DEFAULT NULL,
  `owner_profile_id` bigint unsigned DEFAULT NULL,
  `data_source_instance_id` bigint unsigned NOT NULL COMMENT 'We should change it to Not Null',
  `account_name` varchar(255) DEFAULT NULL COMMENT 'Should be replaced by data_source_instance_id',
  `person_id` bigint unsigned DEFAULT NULL,
  `uploaded_timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `last_sync_timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name_prefix` varchar(255) DEFAULT NULL,
  `original_first_name` varchar(255) DEFAULT NULL,
  `first_name` varchar(30) DEFAULT NULL,
  `additional_name` varchar(255) DEFAULT NULL,
  `original_last_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(30) DEFAULT NULL,
  `full_name` varchar(255) DEFAULT NULL,
  `name_suffix` varchar(255) DEFAULT NULL,
  `nickname` varchar(255) DEFAULT NULL,
  `display_as` varchar(255) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `organization` varchar(255) DEFAULT NULL,
  `organization_profile_id` bigint unsigned DEFAULT NULL,
  `job_title` varchar(255) DEFAULT NULL COMMENT 'TODO Change to job_title_original',
  `job_title_id` int unsigned DEFAULT NULL,
  `job_title_ml_id` bigint unsigned DEFAULT NULL,
  `main_profile_id` bigint unsigned DEFAULT NULL,
  `department` varchar(255) DEFAULT NULL,
  `notes` varchar(1024) DEFAULT NULL,
  `email1` varchar(255) DEFAULT NULL,
  `email2` varchar(255) DEFAULT NULL,
  `email3` varchar(255) DEFAULT NULL,
  `phone1` varchar(255) DEFAULT NULL,
  `phone2` varchar(255) DEFAULT NULL,
  `phone3` varchar(255) DEFAULT NULL,
  `address1_street` varchar(255) DEFAULT NULL,
  `address1_city` varchar(255) DEFAULT NULL,
  `address1_state` varchar(255) DEFAULT NULL,
  `address1_postal_code` varchar(255) DEFAULT NULL,
  `address1_country` varchar(255) DEFAULT NULL,
  `address2_street` varchar(255) DEFAULT NULL,
  `address2_city` varchar(255) DEFAULT NULL,
  `address2_state` varchar(255) DEFAULT NULL,
  `address2_postal_code` varchar(255) DEFAULT NULL,
  `address2_country` varchar(255) DEFAULT NULL,
  `birthday` date DEFAULT NULL,
  `day` int unsigned DEFAULT NULL,
  `month` int unsigned DEFAULT NULL,
  `year` int unsigned DEFAULT NULL,
  `cira` tinyint(1) DEFAULT NULL,
  `anniversary` date DEFAULT NULL,
  `website1` varchar(255) DEFAULT NULL,
  `website2` varchar(255) DEFAULT NULL,
  `website3` varchar(255) DEFAULT NULL,
  `photo_url` varchar(255) DEFAULT NULL,
  `photo_file_name` varchar(255) DEFAULT NULL,
  `source` varchar(255) DEFAULT NULL,
  `visibility_id` bigint unsigned DEFAULT '1',
  `is_test_data` tinyint DEFAULT NULL,
  `start_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `end_timestamp` timestamp NULL DEFAULT NULL,
  `created_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_user_id` bigint unsigned NOT NULL,
  `created_real_user_id` bigint unsigned NOT NULL,
  `created_effective_user_id` bigint unsigned NOT NULL,
  `created_effective_profile_id` bigint unsigned NOT NULL,
  `updated_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_user_id` bigint unsigned NOT NULL,
  `updated_real_user_id` bigint unsigned NOT NULL,
  `updated_effective_user_id` bigint unsigned NOT NULL,
  `updated_effective_profile_id` bigint unsigned NOT NULL,
  PRIMARY KEY (`contact_id`),
  UNIQUE KEY `contact_id_UNIQUE` (`contact_id`),
  UNIQUE KEY `unique_contact_from_data_source_instance` (`first_name`,`last_name`,`email1`,`phone1`,`data_source_instance_id`),
  KEY `owner_profile_id` (`owner_profile_id`),
  KEY `contact.identifier.fk_idx` (`identifier`),
  KEY `data_source_instance_id_idx` (`data_source_instance_id`),
  KEY `contact_table.data_source_instance_id_idx` (`data_source_instance_id`),
  CONSTRAINT `contact.identifier.fk` FOREIGN KEY (`identifier`) REFERENCES `identifier`.`identifier_table` (`identifier`),
  CONSTRAINT `contact_table.data_source_instance_id.fk` FOREIGN KEY (`data_source_instance_id`) REFERENCES `data_source_instance`.`data_source_instance_table` (`data_source_instance_id`),
  CONSTRAINT `contact_table_ibfk_1` FOREIGN KEY (`owner_profile_id`) REFERENCES `profile`.`profile_table` (`profile_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4833 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
